---
title: "SEIR_GBM"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(deSolve)
library(doParallel)
library(doRNG)
library(dplyr)
library(GGally)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(pomp)
library(readsdr)
library(readxl)
library(scales)
library(stringr)
library(tictoc)
library(tidyr)

source("./R_scripts/helpers.R")
```

```{r}
irish_data <- read_excel("./Data/irish_data.xlsx") %>% 
  rename(time = Time,
         y = ReportedCases) %>% select(-CumulativeCases)

first_date      <- as_date("2020-02-29")
last_date       <- first_date + nrow(irish_data) - 1
irish_data$date <- seq(first_date, last_date, 1)
```

```{r}
 ggplot(irish_data, aes(x = date, y = y)) +
  geom_col(colour = "white", fill = "steelblue", alpha = 0.95) +
  theme_pubr() +
  geom_vline(xintercept = as_date("2020-02-29") + 13, colour = "grey50",
             linetype = "dotted") +
  geom_vline(xintercept = as_date("2020-02-29") + 28, colour = "grey10",
             linetype = "dotted") +
  annotate("text", x = as_date("2020-02-29") + 13.5, y = 750, 
           label = "Delay phase", hjust = 0, size = 3, colour = "grey50") +
  annotate("text", x = as_date("2020-02-29") + 28.5, y = 920, 
           label = "Stay at home", hjust = 0, size = 3, colour = "grey50") +
  labs(x = "Date of Lab specimen collection",
       y = "Incidence [new cases per day]") +
  theme(axis.title.y = element_text(size = 8))
```

```{r}
N_val       <- 4999970

B_guess     <- 3 / 5

stock_inits <- list(S = N_val - 1,
                    E = 0,
                    I = 1,
                    R = 0,
                    C = 0,
                    B = 3 / 5)

gamma_val   <- 1 / 5
sigma_val   <- 1 / 3
rho_guess   <- 1 / 2
alpha_val   <- 0.1

consts_vals <- list(N         = N_val,
                    par_gamma = gamma_val,
                    sigma     = sigma_val,
                    rho       = rho_guess,
                    alpha     = alpha_val)

mdl <- read_xmile("./models/GBM_SEIR.stmx", stock_list = stock_inits,
                  const_list = consts_vals)
```

```{r}
set.seed(9)

stop_time <- nrow(irish_data)
test_run  <- sd_simulate(mdl$deSolve_components, start_time = 0, 
                         stop_time = stop_time, timestep = 0.01,
                         integ_method = "euler")
```



```{r}
tic()
set.seed(1712)

stocks_df <- data.frame(E = rep(0, 1200))

runs1_df  <- sd_sensitivity_run(mdl$deSolve_components, stocks_df = stocks_df,
                                timestep = 0.01, multicore = T, n_cores = 6,
                                start_time = 0, stop_time = stop_time,
                                integ_method = "euler")
toc()
```


```{r}
Csnippet("
  y = rpois(C);  
  ") -> rmeas

Csnippet("
  lik = dpois(y,C,give_log) + 1e-5;
") -> dmeas

Csnippet("
  S = 4999969;
  E = 0;
  I = 1;
  R = 0;
  B = B_0;
  C = 0;
  ") -> rinit

Csnippet("
  double dW = rnorm(0,sqrt(dt));
  S-= (B*S*I/N_0)*dt;
  E+= (B*S*I/N_0 - sigma*E)*dt;
  I+= (sigma*E - gamma*I)*dt;
  R+= (gamma*I)*dt;
  B+= alpha*B*dW;
  C+= (rho*sigma*E)*dt;
") -> SEIR_GBM_step

params <- c(N_0 = N_val, gamma = gamma_val, B_0 = B_guess, 
            sigma = sigma_val, alpha = alpha_val, 
            rho = rho_guess)

irish_data %>% select(-date) %>% 
pomp(
  times = "time", t0 = 0,
  rinit = rinit,
  rprocess = pomp::euler(SEIR_GBM_step, delta.t = 0.01),
  statenames = c("S", "E","I", "R", "C", "B"),
  paramnames = c("N_0", "gamma", "B_0", "sigma", "rho", "alpha"),
  params = params,
  accumvars = "C",
  rmeasure = rmeas,
  dmeasure = dmeas,
  partrans = parameter_trans(log   = c("B_0"),
                             logit = c("alpha", "rho"))
) -> SEIR_GBM
```


```{r}
set.seed(1930)
pomp_sims <- pomp::simulate(SEIR_GBM, nsim = 1200) 
runs2_df  <- as.data.frame(pomp_sims)
```

```{r}
B_readsdr <- runs1_df %>% select(iter, time, B) %>% 
  filter(time - trunc(time) == 0, time > 0) %>% 
  mutate(source = "readsdr")

B_pomp <- runs2_df %>% select(.id, time, B) %>% 
  rename(iter = .id) %>% 
  mutate(source = "pomp")

B_df <- bind_rows(B_readsdr, B_pomp)
```

```{r}
ggplot(B_df, aes(x = time, y = B)) +
  geom_line(aes(group = iter), colour = "grey90") +
  facet_wrap(~source) +
  theme_pubr()
```
```{r}
true_inc_df1 <- runs1_df %>% select(iter, time, C) %>% 
  filter(time - trunc(time) == 0) %>% 
  mutate(x = C - lag(C),
         source = "readsdr") %>% 
  filter(time != 0) 

true_inc_df2 <- runs2_df %>% select(.id, time, C) %>% 
  rename(x = C, iter = .id) %>% 
  mutate(source = "pomp")

true_inc_df <- bind_rows(true_inc_df1, true_inc_df2)
```

```{r}
ggplot(true_inc_df, aes(x = time, y = x)) +
  geom_line(aes(group = iter), colour = "grey90") +
  scale_y_continuous(label = unit_format(unit = "K", scale = 1e-3, sep = "")) +
  facet_wrap(~source) +
  theme_pubclean() +
  labs(y = "True reported incidence")
```
```{r}
runs1_df <- NULL
runs2_df <- NULL
gc()
```


## Likelihood

```{r}
registerDoParallel(cores = 6)
registerDoRNG(652643293)

foreach (i = 1:10, .combine = c) %dopar% {
  SEIR_GBM %>% pfilter(Np = 5000)
} -> pf
logLik(pf) -> ll
logmeanexp(ll, se=TRUE)
```

```{r}
slice_design(
  center= coef(SEIR_GBM),
  B_0   = rep(seq(from = 0.1, to = 1.5, length = 40), each = 3),
  rho   = rep(seq(from = 0.1, to = 1, length = 40), each = 3)
) -> p

registerDoParallel(cores = 6)
registerDoRNG(108028909)


# 5 mins
tic()
foreach (theta = iter(p,"row"), .combine = rbind, .inorder=FALSE) %dopar%
    {
      SEIR_GBM %>% pfilter(params = theta, Np = 5000) -> pf
      theta$loglik <- logLik(pf)
      theta
    } -> slice_ll
toc()
```

```{r}
slice_ll %>% filter(!is.infinite(loglik),
                    loglik > max(loglik) - 500) %>% 
  gather(variable, value, B_0, alpha, rho) %>%
  filter(variable == slice) %>%
  ggplot(aes(x = value, y = loglik, color = variable))+
  geom_point() +
  facet_grid(~variable, scales = "free_x")+
  guides(color = FALSE) +
  labs(x="Parameter value",color="") +
  theme_pubr()
```


```{r, lik_surface}
params_bounds <- list(list(name = "rho", min = 0.1, max = 1),
                      list(name = "B_0", min = 0.1, max = 1.5))

combinations  <- combn(1:length(params_bounds), 2, simplify = FALSE)

ll_slice_list <- purrr::map(combinations, function(indexes) {
  i       <- indexes[[1]]
  j       <- indexes[[2]]
  x1_name <- params_bounds[[i]]$name
  x2_name <- params_bounds[[j]]$name
  
  file_path <- str_glue("./Saved_objects/Irish_data/SEIR_GBM/surface_exploration_{x1_name}_{x2_name}.rds")
  
  if(!file.exists(file_path)) {
    p <- create_2d_slices(params_bounds[[i]], params_bounds[[j]],
                          params)    
    
    registerDoParallel(cores = detectCores() - 2)
    registerDoRNG(421776444)
    
    tic.clearlog()
    tic()
  
    foreach (theta = iter(p,"row"), .combine = rbind, .inorder=FALSE) %dopar%
    {
      SEIR_GBM %>% pfilter(params = theta, Np = 5000) -> pf
      theta$loglik <- logLik(pf)
      theta
    } -> p
    
    toc(quiet = TRUE, log = TRUE)
    log.lst <- tic.log(format = FALSE)
    
    p_list  <- list(p = p, time = log.lst)
    saveRDS(p_list, file_path)
  } else {
    p_list <- readRDS(file_path)
  }
  p_list
})
```

```{r}
loglik_df <- ll_slice_list[[1]]$p %>% select(B_0, rho, loglik)
  
loglik_df %>%  
  mutate(loglik=ifelse(loglik>max(loglik)-200,loglik,NA)) %>% 
  ggplot(aes(x= B_0, y= rho,z=loglik,fill=loglik))+
  geom_tile(color=NA)+
  scale_fill_viridis_c()+
  theme_classic() +
  labs(x=expression(B[0]),y = expression(rho))
```




# Local search

```{r}
file_path <- "./Saved_objects/Irish_data/SEIR_GBM/local_search.rds"

if(!file.exists(file_path)) {
  tic.clearlog()
  tic()
  registerDoRNG(482947940)

  foreach(i=1:20,.combine = c) %dopar% {

    SEIR_GBM %>%
        mif2(
          params = params,
          Np = 2000, Nmif = 50,
          cooling.fraction.50 = 0.5,
          rw.sd=rw.sd(B_0 = ivp(0.02), rho = 0.02)
        )
    } -> mifs_local
  toc(quiet = TRUE, log = TRUE)
  log.lst <- tic.log(format = FALSE)
  result_list  <- list(result = mifs_local, time = log.lst)
  saveRDS(result_list, file_path)
} else {
  result_list <- readRDS(file_path)
}

mifs_local <- result_list$result
```

```{r}
mifs_local %>%
  traces() %>%
  melt() %>%
  ggplot(aes(x=iteration,y=value,group=L1,color=factor(L1)))+
  geom_line()+
  guides(color=FALSE)+
  facet_wrap(~variable,scales="free_y")
```

```{r}
registerDoRNG(900242057)

tic()

foreach(mf=mifs_local,.combine=rbind) %dopar% {
  evals <- replicate(10, logLik(pfilter(mf,Np=20000)))
  ll <- logmeanexp(evals,se=TRUE)
  mf %>% coef() %>% bind_rows() %>%
    bind_cols(loglik=ll[1],loglik.se=ll[2])
} -> results
toc()
```

```{r}
pairs(~loglik+B_0+rho, data = results, pch = 16)
```

# Global search

```{r}
file_path <- "./Saved_objects/Irish_data/SEIR_GBM/Global_search.rds"

set.seed(2062379496)

runif_design(
  lower = c(B_0 = 0.05, rho = 0.05),
  upper = c(B_0 = 2, rho = 1),
  nseq  = 300
) -> guesses

if(!file.exists(file_path)) {
  mf1 <- mifs_local[[1]]

  registerDoParallel(cores = detectCores() - 2)
  registerDoRNG(1270401374)

  # 14 hours
  tic()

  foreach(guess=iter(guesses,"row"), .combine=rbind) %dopar% {
    mf1 %>%
      mif2(params = c(unlist(guess))) %>%
      mif2(Nmif = 100) -> mf
    
    replicate(
      10,
      mf %>% pfilter(Np = 100000) %>% logLik()
    ) %>%
      logmeanexp(se=TRUE) -> ll
    
    mf %>% coef() %>% bind_rows() %>%
      bind_cols(loglik = ll[1],loglik.se=ll[2])
  } -> results
toc()
saveRDS(results, file_path)
} else {
  results <- readRDS(file_path)  
}
```
