---
title: "S4 Appendix"
output: 
  pdf_document:
    number_sections: true
header-includes:
  - \usepackage{booktabs}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(doParallel)
library(doRNG)
library(dplyr)
library(imputeTS)
library(lubridate)
library(pomp)
library(purrr)
library(readr)
library(readxl)
library(tidyr)
library(stringr)
library(tictoc)

folder <- "./Saved_objects/Irish_data/SEI3R_GBM/mdl_1"
```


# Daily case counts

```{r}
source("./R_scripts/irish_data.R")
irish_data   <- get_irish_data()

source("./R_scripts/apple.R")
drv_data_obj <- get_driving_data()

daily_df <- data.frame(time = 1:79, 
                       y1 = irish_data$y,
                       y2 = drv_data_obj$df$y2)
```

```{r}
#===============================================================================
# Model setup
#===============================================================================

source("./R_scripts/POMP_models.R")

par_obj  <- get_params("GBM_1")
params   <- par_obj$all
pomp_mdl <- get_POMP_model(daily_df, params, 1 / 128)
```


```{r}
source("./R_scripts/likelihood_funs.R")
source("./R_scripts/helpers.R")

path <- "./Saved_objects/Irish_data/SEI3R_GBM/weekly/mdl_2/top_10.csv"
test_pars <- read_csv(path)
pars_list <- transpose(test_pars)

imap_dfr(pars_list, function(pars_set, i) {
  n_particles <- c(5e3, 1e4, 2e4)
  fn <- file.path(folder, str_glue("pf_sensitivity_{i}.rds"))
  pars <- c(unlist(pars_set), par_obj$fixed)
  
  pomp_mdl <- pomp_mdl %>% pomp(params = pars)
  
  pf_sensitivity(n_particles = n_particles, n_cores = 7, 
                 seed = 873446145, pomp_mdl = pomp_mdl, fn = fn,
                 n_iter = 14) %>% 
    mutate(set_id = i)
}) -> sens_df
```

```{r}
library(ggplot2)
library(ggpubr)
ggplot(sens_df, aes(x = Np, y = loglik)) +
  scale_x_log10() +
  geom_point(colour = "#C7C2F9") +
  geom_line(stat = "smooth", method = "loess", formula = y ~ x, alpha = 0.15,
            colour = "#C7C2F9", size = 1) +
  facet_wrap(~set_id) +
  theme_pubr()
```

```{r}
ggplot(sens_df, aes(x = Np, y = loglik.se)) +
  scale_x_log10() +
  scale_y_log10() +
  geom_point(colour = "#C7C2F9") +
  geom_line(stat = "smooth", method = "loess", formula = y ~ x, alpha = 0.15,
            colour = "#C7C2F9", size = 1) +
  facet_wrap(~set_id, scales = "free_y") +
  theme_pubr()
```

